# Generated by Django 4.2.6 on 2024-12-08 20:06

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('general_category', models.CharField(choices=[('ML', 'ML'), ('Developement', 'Development'), ('Blockchain', 'Blockchain'), ('CP', 'CP'), ('Others', 'Others')], default='Others', max_length=255)),
                ('specific_category', models.CharField(default='NA', max_length=255)),
                ('mentee_max', models.CharField(max_length=255)),
                ('mentor', models.CharField(default='NA', max_length=255)),
                ('description', models.TextField(default='NA')),
                ('timeline', models.TextField(default='NA')),
                ('checkpoints', models.TextField(default='NA')),
                ('prerequisites', models.TextField(default='NA')),
                ('co_mentor_info', models.TextField(default='NA')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=projects.models.upload_to)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenteePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.TextField()),
                ('preference', models.IntegerField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('mentee', 'project', 'preference'), ('mentee', 'project')},
            },
        ),
        migrations.AddField(
            model_name='mentee',
            name='preferences',
            field=models.ManyToManyField(help_text='The projects that the mentee has applied to.', related_name='applications', through='projects.MenteePreference', to='projects.project'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='project',
            field=models.ForeignKey(help_text='The project that the mentee has been selected for. Is NULL if not selected yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.OneToOneField(help_text='The user corresponding to the mentee.', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='MenteeWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('mentee', 'project')},
            },
        ),
    ]
