# Generated by Django 4.2.6 on 2024-04-04 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'First Mentor'), (2, 'Rejected'), (3, 'Accepted')], default=0)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=projects.models.default_season_name, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Yet To Start'), (10, 'Mentor Registration'), (15, 'Mid Mentor Mentee'), (20, 'Mentee Registration'), (30, 'Ongoing')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('mentee_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('mentee_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('abstract', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('timeline', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=projects.models.upload_to)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectcategory')),
                ('mentors', models.ManyToManyField(through='projects.MentorRequest', to='projects.mentor')),
                ('season', models.ForeignKey(default=projects.models.get_current_id, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.season')),
            ],
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='season',
            field=models.ForeignKey(default=projects.models.get_current_id, help_text='The season to which mentee is applying for.', on_delete=django.db.models.deletion.PROTECT, to='projects.season'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(help_text='The user corresponding to the mentee.', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='MenteePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.TextField()),
                ('ordering', models.IntegerField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='mentee',
            name='preferences',
            field=models.ManyToManyField(help_text='The projects that the mentee has applied to.', related_name='applications', through='projects.MenteePreference', to='projects.project'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='season',
            field=models.ForeignKey(default=projects.models.get_current_id, help_text='The season to which mentee is applying for.', on_delete=django.db.models.deletion.PROTECT, to='projects.season'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.ForeignKey(help_text='The user corresponding to the mentee.', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='mentor',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='mentor_unique_user_season'),
        ),
        migrations.AddConstraint(
            model_name='mentee',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='mentee_unique_user_season'),
        ),
    ]
