# Generated by Django 4.2.6 on 2024-04-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorrequest',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentors',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='MentorRequest',
        ),
    ]
