# Generated by Django 4.2.6 on 2024-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_mentorrequest_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentee_min',
        ),
        migrations.AddField(
            model_name='project',
            name='checkpoints',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='project',
            name='co_mentor_info',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='project',
            name='prereuisites',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentee_max',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.TextField(default='NA'),
        ),
    ]
