# Generated by Django 4.2.6 on 2024-04-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_abstract_remove_project_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='description',
        ),
    ]
