# Generated by Django 4.2.6 on 2024-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='general_category',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('Developement', 'Development'), ('Blockchain', 'Blockchain'), ('CP', 'Cybersecurity'), ('Others', 'Others')], default='Others', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='specific_category',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
