# Generated by Django 4.2.6 on 2024-04-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_category_project_general_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='general_category',
            field=models.CharField(choices=[('ML', 'ML'), ('Developement', 'Development'), ('Blockchain', 'Blockchain'), ('CP', 'CP'), ('Others', 'Others')], default='Others', max_length=255),
        ),
    ]
