# Generated by Django 4.2.6 on 2024-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_general_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentee',
            name='mentee_unique_user_season',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='preferences',
        ),
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='menteepreference',
            unique_together={('mentee', 'project')},
        ),
    ]
