# Generated by Django 4.2.6 on 2024-04-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_mentee_mentee_unique_user_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menteepreference',
            old_name='ordering',
            new_name='preference',
        ),
        migrations.AlterUniqueTogether(
            name='menteepreference',
            unique_together={('mentee', 'project', 'preference')},
        ),
        migrations.CreateModel(
            name='MenteeWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('mentee', 'project')},
            },
        ),
    ]
