# Generated by Django 4.2.5 on 2023-10-09 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenteePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.TextField()),
                ('ordering', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='mentee',
            name='preferences',
            field=models.ManyToManyField(through='dashboard.MenteePreference', to='projects.project'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='season',
            field=models.ForeignKey(default=projects.models.get_current_id, on_delete=django.db.models.deletion.PROTECT, to='projects.season'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mentee',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='unique_user_season'),
        ),
    ]
