# Generated by Django 4.2.6 on 2023-10-07 12:32

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference1', models.CharField(choices=[('Deep Carlsen', 'Deep Carlsen'), ('InstiExchange', 'Instiexchange'), (' Image Captioning', 'Image Captioning'), ('CricBuzz', 'Cricbuzz'), ('SynerG Lab', 'Synerg Lab')], max_length=255)),
                ('Preference2', models.CharField(choices=[('Deep Carlsen', 'Deep Carlsen'), ('InstiExchange', 'Instiexchange'), (' Image Captioning', 'Image Captioning'), ('CricBuzz', 'Cricbuzz'), ('SynerG Lab', 'Synerg Lab')], max_length=255)),
                ('Preference3', models.CharField(choices=[('Deep Carlsen', 'Deep Carlsen'), ('InstiExchange', 'Instiexchange'), (' Image Captioning', 'Image Captioning'), ('CricBuzz', 'Cricbuzz'), ('SynerG Lab', 'Synerg Lab')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='season',
            field=models.ForeignKey(default=dashboard.models.SeasonManager.current_id, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='dashboard.season'),
        ),
    ]
